DIGOAI/chatbot-backend

src/config/config.py
- Renamed `DB_USER` -> `PGUSER` env variable.
- Renamed `DB_PASSWORD` -> `PGPASSWORD` env variable.
- Renamed `DB_HOST` -> `PGHOST` env variable.
- Renamed `DB_PORT` -> `PGPORT` env variable.
- Renamed `DB_NAME` -> `PGDATABASE` env variable.
- Added `DATABASE_URL` env variable.
=> :wrench: Updated env variables names.

Pipfile, Pipfile.lock, src/db/models/__init__.py, src/models/__init__.py, src/models/auth.py, src/models/user.py, src/repositories/__init__.py, src/repositories/user_repository.py, src/routes/__init__.py, src/routes/auth_routes.py, src/use_cases/__init__.py, src/use_cases/auth_use_cases.py, src/utils/__init__.py, src/utils/encrypt.py, src/utils/patterns.py
- Added `passlib[bcrypt]==1.7.4` dependecy.
- Updated `pydantic` with `pydantic[email]==2.3.0` dependecy.
- Added `PASSWORD_PATTERN` regex.
- Added `CI_RUC_PATTERN` regex.
- Added `PHONE_PATTERN` regex.
- Added `UUIDV4_PATTERN` regex.
- Added `decrypt` function.
- Added `encrypt` function.
- Added `User` model schema.
- Moved `UserRole` enum class to same file of `User`.
- Fixed minor imports.
- Added `TokenSchema` model class.
- Added `LoginSchema` model class.
- Added `RegisterSchema` model class.
- Implemented `UserRepository` class.
- Implemented `create` repository method.
- Implemented `get_user_by_email` repository method.
- Implemented `RegisterNewUser` use case class.
- Implemented `LoginUser` use case class.
- Implemented `/auth/login` endpoint.
- Implemented `/auth/register` …
=> Feat users admin

Pipfile, Pipfile.lock, src/models/context.py, src/routes/__init__.py, src/routes/external_routes.py, src/services/__init__.py, src/services/saragurosnet.py
- Renamed `SaragurosService` class to `SaragurosNetService`.
- Fixed imports.
- Added `python-multipart==0.0.6` dependency.
- Added `/api/v1/client/deactivate` endpoint.
- Added `/api/v1/client/activate` endpoint.
- Added `/api/v1/invoice/check` endpoint.
- Added `/api/v1/messages/send` endpoint.
- Added `/api/v1/ticket/create` endpoint.
=> Feat external services

src/middlewares/error_handler.py, src/models/__init__.py, src/models/webhook.py, src/repositories/client_repository.py, src/routes/__init__.py, src/routes/client_routes.py, src/routes/external_routes.py, src/routes/message_routes.py, src/routes/twilio_routes.py, src/use_cases/__init__.py, src/use_cases/client_use_cases.py
- Now error handler print error in console.
- Added `GetClientByPhone` use case.
- Added `get_client_by_phone` function.
- Added `get_client_by_phone` route.
- Added `TwilioWebHook` event model.
- Added `/api/v1/twilio/hook` endpoint.
- Move routes to same path root.
- Barrelled imports.
=> Feat backlamd iam

src/config/config.py, src/db/database.py
- Replaced the verify method for a env variables.
- Replace old URL construction with `DATABASSE_URL` env variable.
=> Fix config variables

main.py, src/db/__init__.py
- Removed `setup_db` function.
- Fixed imorts.
=> :fire: Remove setup db step.

src/routes/twilio_routes.py
- Now the webhook response to Twilio with message in `XML`.
- Fixed the `content-type` header response from twilio hook.
=> Add response to Twilio webhook request.

src/api/routes/twilio_routes.py
- Setted correct default value in `last_state` context attribute.
=> :bug: Fix minor bug.

src/saragurosnet/bussiness/__init__.py, src/saragurosnet/bussiness/types/message_types.py
- Fixed a `INVOICES_PENDING` WhatsApp message template.
- Added `button_text` verification to message.
=> Feat chatbot use services

src/saragurosnet/bussiness/types/media_types.py
- Fixed media url for coverages.
=> :bug: Fix media url content.

src/db/models/base.py
- Fixed error when init new conversation after end other conversation, repeat same uuid.
=> :ambulance: Fix init new conversation error.

.vscode/settings.json, migrations/versions/20231026_132553_add_email_column_to_client_table.py, src/common/models/client.py, src/common/services/mock_data.py, src/db/models/client.py
- Oculted unnecesaries files and folders.
- Created `Add email column to client table` migration file.
- Added `email` attribute to `Client` schema classes.
- Added `email` attribute to `Client` model class.
- Update mock data.
=> Feat add email to client model.

src/api/routes/conversation_routes.py
- Now the conversations returned a last message.
=> :clown_face: Update conversations mocked.

src/api/routes/conversation_routes.py, src/common/cases/conversation_cases.py, src/saragurosnet/bussiness/__init__.py
- Added `update_last_message_id` case method.
- Add `ConversationResume` dataclass.
=> Fix conversation resume

src/api/routes/message_routes.py, src/common/cases/message_cases.py, src/common/models/__init__.py, src/common/models/message.py
- Added `MessageInserWeb` schema class.
- Added `send_message_from_web` case method.
- Updated `/api/v1/message/send_message` endpoint.
=> :sparkles: Feature send message from web.

src/common/cases/conversation_cases.py
- Now the `get_conversations_with_last_message` case method.
=> :feat: Return ordered converations.

src/common/cases/conversation_cases.py
- Now the conversations is returning desc by `updated_at`.
- Now end a conversation register correctly the timestamp.
=> Feat send message web

src/common/cases/message_cases.py, src/saragurosnet/bussiness/__init__.py
- Added feature for register message when chatbot send message.
=> :sparkles: Feature register send message.

src/api/cases/whatsapp_use_cases.py, src/api/routes/whatsapp_routes.py, src/common/models/whatsapp.py
Updated whatsapp send messages endpoints
=> ✨ [UPDATE] whatsapp api

src/api/cache/__init__.py, src/api/routes/whatsapp_routes.py, src/common/cases/whatsapp_cases.py, src/common/models/whatsapp.py, src/common/utils/twilio.py
- Removed unnucesary code.
- Refactor WhatsApp sending logic.
=> 🐛♻️ Refactor a WhatsApp massive messages.

src/api/dependencies/__init__.py, src/api/dependencies/cache.py, src/api/routes/twilio_routes.py, src/common/cases/conversation_cases.py, src/common/cases/ticket_cases.py, src/saragurosnet/bussiness/context.py, src/saragurosnet/bussiness/end_actions.py, src/saragurosnet/bussiness/initial_actions.py, src/saragurosnet/bussiness/no_client_actions.py, src/saragurosnet/types/message_types.py
Previously, conversations were not being cached, leading to unnecessary database queries. This pull request adds cache functionality for conversations, improving performance by reducing database queries.
Description
This pull request introduces cache functionality for conversations in order to optimize performance. It includes the following changes:
- Added `CacheConversationTuple` dataclass to store conversation-related information in the cache.
- Created `ConversationCache` class to manage the conversations cache.
- Modified `ConversationUseCases` to retrieve conversations from the cache when available.
- Updated `TicketUseCases` to add conversations to the cache when attending tickets.
- Updated `TicketUseCases` to remove conversations from the cache when closing tickets.
These changes …
=> ♻️✨ Add cache functionality for conversations.
